[Spring MVC(인증)] 안금서 미션 제출합니다.
next-step/spring-basic-roomescape-playground pull request #102
Opened 2024-12-26 05:56 UTC by goldm0ng

.

2025-01-01 14:50 UTC, BackFoxx requested changes
안녕하세요 금서님! 그리디에 처음 합류할 때부터 금서님께서 짱 잘하시고 또 열심히 임하신다는 이야기를 많이 들었습니다. 아니나 다를까 깔끔한 멋쟁이 코드를 작성해 주셨네요. :D

---

1. 금서님께서 겪으신 WeakKeyException은 아쉽게도 제 노트북 환경에서 재현되지 않았습니다. 
SHA 키를 만드는 데에 사용하는 hmacShaKeyFor(byte[] bytes) 메서드는 파라미터로 넘어온 키의 바이트 길이에 알맞은 암호화 알고리즘을 찾아 사용하는데, 기본으로 HS256, HS384, HS512 이렇게 세 개가 있습니다.
미션 예시에서 사용하는 "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=" 문자열의 바이트 길이가 352이기 때문에 그에 맞는 알고리즘인 HS256를 사용해 정상 작동이 되었어야 하지만
금서님 노트북의 라이브러리 버전 차이 등의 이유로 HS256이 없고 HS512만 있어 발생한 문제로 보입니다.
하지만 이 미션에서는 어떤 알고리즘을 쓰든 잘 작동하기만 하면 되니 금서님의 해결 방법은 멋쟁이 해결 방법입니다. 잘 하셨습니다. >:D

---

2. 클라이언트의 의도를 파악할 수 있는 다른 수단이 있다면 클라이언트 코드를 보지 않아도 됩니다. 예를 들어 요구사항 문서가 지금보다 더 상세하게 적혀 있다던가, 어떤 API를 어떤 때에 호출한다는 내용이 상세히 적힌 API 문서가 있다면 더할 나위 없이 좋을 것입니다.
하지만 이번 미션을 포함하여 대부분의 상황에서 이렇게 친절한 문서는 존재하지 않을 것입니다. 문서로 얻을 수 있는 정보가 부족할 땐 클라이언트 코드를 직접 찾아보며 힌트를 얻는 것이 가장 정확하고 직접적인 방법입니다.
제가 일하는 회사에서도 요청/응답 포맷이나 예외 처리 방법을 참고하기 위해 프론트엔드 개발자분께 여쭈어보거나, 제가 직접 클라이언트 코드를 열어 분석하는 일을 엄청 자주 합니다.

---

3, 4. 
제가 생각하는 개선 포인트를 앞으로의 일주일 동안 리뷰 코멘트로 남기겠습니다.
부담이 되지 않게 한 번에 남기는 코멘트의 수를 적게 하는 대신 빠르고 자주 남겨드릴게요. 
답변이 급히 필요하신 경우에는 디스코드의 DM 등으로 연락주시면 더 빠르게 답변을 드릴게요.
함께 멋지게 개선해 보아요! :)

2025-01-01 14:50 UTC, BackFoxx commented on src/main/java/roomescape/authentication/AuthAdminRoleInterceptor.java
> +public class AuthAdminRoleInterceptor implements HandlerInterceptor {
금서님께서 'login', 'authentication', 'jwt' 패키지를 구분하신 기준이 궁금합니다.
기본 제공된 코드의 구조에 맞추어서 도메인 별로 패키지를 구분하신 것 같은데요,
얼핏 생각하기에 login과 authentication은 뜻 차이가 거의 없고,
jwt는 인증의 수단 중 하나이니 authentication에 포함되는 관계가 아닌가- 라는 생각이 들었어요.

2025-01-01 14:50 UTC, BackFoxx commented on src/main/java/roomescape/jwt/JwtProvider.java
> +    }
1. 이 메서드는 JwtUtils의 static 메서드로 만들지 않고 별도의 JwtProvider로 분리하셨습니다. 이유를 알 수 있을까요?

2025-01-01 14:50 UTC, BackFoxx commented on src/main/java/roomescape/jwt/JwtProvider.java
> +    }
2. 
```
} catch (JwtException e) {
    throw new JwtProviderException("JWT 생성에 실패하였습니다.");
}
```
이 코드는 에러 추적의 관점에서 문제가 하나 있습니다. 어떤 문제가 있을까요?

2025-01-01 14:50 UTC, BackFoxx commented on src/main/java/roomescape/login/LoginController.java
> +    public ResponseEntity<LoginCheckResponse> checkLogin(HttpServletRequest request) {
일반적으로 컨트롤러의 반환 타입으로 ResponseEntity<>를 사용하면
비즈니스 로직의 상황에 따라 다양한 httpStatus를 지정하여 응답할 수 있다는 장점이 있습니다.
```
예시) 

try {
    doSomethong();
    return ResponseEntity.ok().build();
} catch (NotLoginException e) {
    return ResponseEntity.status(401).build();
} catch (IllegalStateException e) {
    return ResponseEntity.badRequest().build();
}
```

그런데 현재 컨트롤러 구조에서는
비즈니스 작업을 수행하다 예외가 발생했을 때
status를 401 또는 500으로 변환하여 응답하는 작업을 모두 ExceptionHandler에서 진행합니다.

그렇다면 LoginController 자체는 httpStatus를 분기하지 않고 언제나 ok를 응답하는데,
응답 타입으로 ResponseEntity를 사용할 필요가 있을까요?

2025-01-01 14:50 UTC, BackFoxx commented on src/main/java/roomescape/jwt/JwtUtils.java
> +    public static MemberAuthInfo extractMemberAuthInfoFromToken(String token) {
JwtUtils의 메서드는 static 메서드인데 secretKey라는 인스턴스 변수를 필요로 했습니다.
하지만 static 메서드는 인스턴스 변수에 접근할 수 없으니 secretKey 변수를 static한 클래스 변수로 만들었습니다.
스프링은 클래스 변수에 자동 주입을 해주지 않으니 인스턴스 메서드인 setScretKey()를 만들고 스프링이 사용하게끔 우회하셨습니다.

작성하시면서도 느끼셨겠지만 static 메서드에 주위 환경을 끼워맞추는 과정에서 점점 찜찜하고 부자연스러운 구조가 되었습니다.
이 클래스는 스프링이 없으면 단위 테스트를 하기도 어렵고, 동시성 측면에서 위험한 코드이기도 합니다.

---

자바의 정석 서적을 집필하신 멋쟁이 강사님께서 static 메서드에 대해 설명해주신 영상이 있습니다.
https://youtu.be/Fl4TzjPKAMU?si=JtddEqhCV7B127-A

위 영상을 참고해서 아래 두 질문의 답을 고민해주셨음 좋겠습니다.

* 자바에서 static 메서드는 어떤 경우에 사용하나요?
* JwtUtils의 메서드들은 static이어야 하는 메서드인가요? 그 이유는 무엇인가요?

2025-01-01 14:50 UTC, BackFoxx commented on src/main/java/roomescape/login/LoginRequest.java
> +}
이 친구는 record 대신 @Data를 사용하신 이유가 있나요? :D

2025-01-07 16:17 UTC, goldm0ng commented on src/main/java/roomescape/login/LoginRequest.java
> +}
아니요! 딱히 이유는 없습니다.. ㅎㅎ 그러고 보니, 새로 만든 DTO 중 LoginRequest만 이 방식으로 했네요. 그리디 미션하면서 lombok을 처음 학습해보고 적용해본 후 손에 익어버려서 저도 모르게 그만...!!! @Data 는 record 와 달리 Setter 기능까지 다 쓸 수 있도록 열려있어서 객체의 불변성을 보장하지 못한다는 측면에서 위험하다고 생각합니다. 앞으로 DTO를 생성할 때에는 record 타입으로 생성하도록 하겠습니다~!

그리고 질문과는 별개로 lombok이 제공하는 기능 중, @RequiredArgsConstructor 라는 것도 생성자 주입 대신 간단히 어노테이션 하나만 붙이면 자동으로 생성자 주입이 가능해서 편하게 쓰고 있는데 이런 자잘한 편의성을 위해 lombok 라이브러리를 쓰는 것에 대해 어떻게 생각하시나요? 현업에서는 lombok을 많이 쓰는 편인지도 궁금합니다!

2025-01-07 17:12 UTC, goldm0ng commented on src/main/java/roomescape/login/LoginController.java
> +    public ResponseEntity<LoginCheckResponse> checkLogin(HttpServletRequest request) {
예리한 말씀이시네요 여우님! 생각도 못하고 있었던 부분이에요 ... 🦊
Spring 미션을 시작한 이후로 RestController에서 항상 ResponseEntity로 응답을 내려줬어서 더 그랬던 것 같네요. 찾아보니, 반환값이 없을 때 예외가 발생하지 않은 경우를 성공적인 요청으로 간주해 @RestController가 자동으로 HTTP 상태 코드 200 OK 를 추가한다는 기본적인 내용을 모르고 있었네요.. 여우님 덕분에 알아갑니다!  저는 200 OK 라도 직접 ResponseEntity로 응답을 내려줘야 하는 줄 알았습니다! 

말씀해주신 내용 바탕으로 코드 수정하겠습니다:)

2025-01-08 01:12 UTC, goldm0ng commented on src/main/java/roomescape/authentication/AuthAdminRoleInterceptor.java
> +public class AuthAdminRoleInterceptor implements HandlerInterceptor {
사실 패키지 구분하는 것이 제일 모호하고 어려운 일인 것 같아요.
명확한 기준이 있어서 구분했다기 보다는, 미션 단계별로 미션을 구현해 나가는 과정에서 자연스럽게 추가되다 보니 저렇게 나뉜 것 같네요. 최대한 가독성(?) 있게 보이고자 했고, 각 패키지가 맡은 역할을 분리하려고 했습니다! 

> 얼핏 생각하기에 login과 authentication은 뜻 차이가 거의 없고,

제가 미션 당시 패키지를 나눈 이유는, 두 개념의 역할과 범위를 조금 더 명확하게 구분하기 위해서였던 것 같아요! login은 사용자 로그인 요청/응답과 관련된 책임을 다루고, authentication은 이후 요청에서 인증 상태를 확인하고 그에 맞는 관련 응답을 내리는 책임을 다루도록 했습니다. 구현 당시엔 '로그인 패키지에는 로그인 관련 로직만! ' , '다른 인증 로직은 따로 분리해서 처리해야지!' 라는 생각으로 생각했었는데, 다시 생각해보니 여우님 말씀도 일리가 있네요. 따지고 보면 로그인도 인증 과정 중 하나인 거잖아요? 흠,, 이 부분에 대해서는 고민을 좀 더 해보겠습니다! 

> jwt는 인증의 수단 중 하나이니 authentication에 포함되는 관계가 아닌가- 

여우님 말씀대로 jwt는 인증의 수단 중 하나이므로, authentication 패키지에 포함시키는 것이 더 일관성 있고 직관적인 구조일 수 있을 것 같네요! 생각해보니, 인증이라는 하나의 도메인에서 관리하는 것이 더 적합할 것 같고 패키지 간 의존성을 줄이는 데도 도움이 될 것 같아요.

패키지 구조에 대해 좀 더 생각해보고 리뷰 반영하겠습니다~!

Q1. 아 그리고 여우님은 패키지 구조를 나눌 때 여우님만의 명확한 기준이 있나요? 
저는 항상 패키지를 나눌 때 약간의 어려움이 있는 것 같아요. 얼핏 보면 A라는 패키지에 포함되는 것 같기도 하고, B라는 패키지에 포함되는 것 같기도 하는... 그런 애매모호한 경우 말이죠,,, 여우님만의 패키지 분리 팁을 알려주실 수 있나요? 

Q2. 그리고 가독성과 코드 유지보수성 측면에서, 
패키지를 최대한 작게 나누는 게 좋을까요? 아니면 조금이라도 포함되는 관계는 포함시켜서 패키지 덩어리를 크게 크게 나누는 게 좋을까요?

2025-01-08 01:26 UTC, goldm0ng commented on src/main/java/roomescape/jwt/JwtProvider.java
> +    }
1. 우선, JwtProvider와 JwtUtils를 분리한 이유는 역할과 책임을 명확히 구분하고 싶어서였습니다! JwtProvider은 JWT 생성과 관련된 로직만을 담당하고, JwtUtils 는 JWT 검증 및 파싱, 쿠키에서 토큰을 추출하는 등의 유틸리티 작업 위주의 로직이 존재합니다. 

2. 발생한 예외의 상세 정보를 누락한다는 점이 문제인 것 같습니다! JwtException을 JwtProviderException으로 전환할 때 원래 발생한 예외를 포함하지 않아, 디버깅 및 문제 해결 과정에서 원인을 파악할 수 어렵게 만들 수가 있겠네요. 지금은 간단한 애플리케이션이라 괜찮을 수 있어도, 규모가 훨씬 커질 경우 정말 큰 문제가 될 수 있겠다는 생각도 들어요,, 해당 코드는 즉시 수정하도록 하겠습니다!!!

2025-01-08 02:23 UTC, goldm0ng commented on src/main/java/roomescape/jwt/JwtUtils.java
> +    public static MemberAuthInfo extractMemberAuthInfoFromToken(String token) {
> 위 영상을 참고해서 아래 두 질문의 답을 고민해주셨음 좋겠습니다.

Q1. 자바에서 static 메서드는 어떤 경우에 사용하나요?
Q2. JwtUtils의 메서드들은 static이어야 하는 메서드인가요? 그 이유는 무엇인가요?

영상을 본 후 강의에서 얻은 위 질문에 대한 해답을 말씀드릴게요.
A1. 
     1. 속성 (멤버 변수) 중에서 공통 속성에 static을 붙인다. 
     2. 인스턴스 멤버를 사용하지 않는 메서드에 static을 붙인다.
  
    강의 내용 외의 답변도 찾아봤습니다.
    3. 클래스 수준의 불변 데이터(final static)만을 참조하는 경우 ex) 상수 관련
    4. 유틸리티성 로직 - "객체 상태"에 의존하지 않는 메서드로 클래스의 기능을 제공하기 위한 용도로 사용된다. ex) Math.sqrt(), Collectoins.sort()
    5. 객체 생성 없이 호출이 필요한 경우

A2.

2025-01-08 10:29 UTC, BackFoxx commented on src/main/java/roomescape/login/LoginController.java
> +    public ResponseEntity<LoginCheckResponse> checkLogin(HttpServletRequest request) {
히히 짱 ! :D :D

2025-01-08 10:51 UTC, BackFoxx commented on src/main/java/roomescape/jwt/JwtUtils.java
> +    public static MemberAuthInfo extractMemberAuthInfoFromToken(String token) {
열심히 공부해주셔서 정말 멋지고 감사해요 금서님!
자바 언어를 사용하는 많은 사람들이 항상 어려워하는 것이
이 필드는 static인가 아닌가 ,, 이 메서드는 static인가 아닌가 ,, 라서
이번 기회에 static과 그렇지 않은 것을 정하는 기준을 잘 잡으신 것 같아 뿌듯해요.

static을 떼는 것 외에 또다른 해결방법으로는
secretKey를 JwtUtils의 필드로 두지 말고 각 static 메서드의 파라미터로 받아 사용하는 것도 있어요.
하지만 Jwt와 밀접한 관련이 있는 secretKey를 외부에서 생성해 파라미터로 받는다는 것도 꽤 어색한 상황이 될 수 있으니
그때그때 잘 판단해서 최선의 방법을 쓰면 될 것 같아요.

---

코멘트에 '유틸성 로직' 이라는 키워드가 마침 있으니 관련 질문을 하나 더 드릴게요!
'유틸성 클래스' 라는 키워드를 한 번 알아보신 후,
아래 질문에 대해 고민해주세요!

* JwtUtils는 유틸성 클래스인가요?

2025-01-08 12:39 UTC, BackFoxx commented on src/main/java/roomescape/login/LoginRequest.java
> +}
회사에서도 lombok을 씁니다! 정말 짱짱 편해서 자바를 사용하는 모든 프로젝트에서 사용해요.
회사를 한 군데만 다녀봐서 '실무에선 이걸 써요 !' 하기는 어렵지만, 제 회사에서 쓰는 대표적인 롬복을 공유할게요.

### Getter
거의 모든 엔티티에 붙이는 어노테이션입니다! 
한창 클린코드를 공부할 땐 '[무분별한 getter 사용도 위험한 것 아닌가?](https://velog.io/@backfox/getter-%EC%93%B0%EC%A7%80-%EB%A7%90%EB%9D%BC%EA%B3%A0%EB%A7%8C-%ED%95%98%EA%B3%A0-%EA%B0%80%EB%B2%84%EB%A6%AC%EB%A9%B4-%EC%96%B4%EB%96%A1%ED%95%B4%EC%9A%94)' 라는 생각에 꼭 필요한 필드만 getter 메서드를 직접 달고 @Getter를 사용하지 않았지만, 회사에서 개발해보니 매 엔티티마다 엔티티의 구성요소를 거의 그대로 꺼내와 응답하는 조회 API가 항상 있었고, 그러다보니 결국엔 엔티티의 모든 필드에 대한 getter 메서드가 생기게 되더라구요.
이럴 땐 @Getter를 써서 간편히 조회 메서드를 만드는 것이 훨씬 좋은 생산성을 가져다 주었습니다 :D

### RequiredArgsConstructor
이것도 짱 많이 씁니다! 주로 컨트롤러, 서비스, 리포지토리 같은 컴포넌트 클래스에 사용하고,
엔티티같은 도메인 클래스에는 거의 사용하지 않습니다. 왜일까요? :0

여기 어떤 원태연이라는 도메인 클래스가 있다고 해보아요.
```java
@RequiredArgsConstructor
public class 원태연 {
    private final int age;
    private final int iq;
}
```

@RequiredArgsConstructor는 필드의 선언 순서에 맞추어 생성자의 파라미터 순서를 정해줘요.
그럼 생성자는 new 원태연(나이, IQ) 이렇게 되겠네요.
객체를 생성할 땐 대충 아래와 같이 만들 수 있겠죠?
```java
var 원태연 = new 원태연(26, 150);
// 26세, IQ 150
```

그런데 어느날 금서님의 동료가 어쩌다보니 원태연 클래스의 필드 순서를 쇽 바꿨어요.
```java
@RequiredArgsConstructor
public class 원태연 {
    private final int iq;
    private final int age;
}
```

필드의 순서가 바뀌면 롬복이 만들어주는 생성자의 파라미터 순서도 같이 바뀌어요, 
new 원태연(IQ, 나이) 이렇게요.
그럼 아까 적은 코드는 어떻게 어떤 객체를 만들게 될까요?

```java
var 원태연 = new 원태연(26, 150);
// 150세, IQ 26 !!!!! :0 :0
```

컴포넌트성 클래스에 비해 도메인 클래스는 우리가 직접 생성자를 호출해 객체를 만드는 빈도가 훨씬 높기 때문에, 재수가 없으면 엔티티의 필드를 수정하거나 추가하면서 순서가 살짝만 바뀌어도 객체가 완전 이상한 정보를 담게 되는 참사가 일어날 수 있어요.
@RequiredArgsConstructor 뿐만 아니라 모든 필드에 대한 생성자를 만들어주는 @AllArgsConstructor도 똑같은 위험성을 가지고 있습니다.

이와 같은 문제를 예방하기 위해,
제가 다니는 회사에서는 도메인 클래스에 @RequiredArgsConstructor 대신 후술할 @Builder를 사용하는 것을 규칙으로 하고 있어요.

### Builder
빌더 패턴에서 파생되어, 빌더 코드를 쉽게 만들어주는 @Builder 어노테이션이에요!
```java
var 원태연 = 원태연.builder()
                .iq(150)
                .age(26)
                .build();
```
이런 방식으로 사용할 수 있는데요,
빌더를 사용해서 객체를 생성하면 내가 어떤 필드에 값을 지정할 지 하나하나 명확하게 명시하기 때문에
클래스의 필드 순서가 바뀌어도 전혀 지장이 생기지 않아요!

상황에 따라 여러 종류의 빌더를 만들 수도 있고, 빌더의 이름도 지정할 수 있으니
따로 학습해서 다음 미션이나 프로젝트에서 응용해보시는 것도 좋을 것 같아요! :)

2025-01-08 14:12 UTC, BackFoxx commented on src/main/java/roomescape/authentication/AuthAdminRoleInterceptor.java
> +public class AuthAdminRoleInterceptor implements HandlerInterceptor {
> login은 사용자 로그인 요청/응답과 관련된 책임을 다루고, authentication은 이후 요청에서 인증 상태를 확인하고 그에 맞는 관련 응답

사실 저도 이게 맞다고 생각하고 있어요! 로그인은 '나는 이 서비스의 회원이에요' 라고 **주장**하는 도메인, 인증은 '당신은 이 서비스의 회원인가요?' 하고 **검증**하는 도메인이라고 할 수 있으니,
'인증' 이라는 동일한 키워드를 다루면서도 그 목적과 결과가 다르죠.
하지만 로그인과 인증의 경계는 정말로 사람의 관점에 따라 다른 것 같아요. 언젠가 다른 관점을 가진 사람을 만나면 더 멋진 토론을 할 수 있겠네요.

---

> Q1. 패키지 구조를 나눌 때의 명확한 기준이 있나요?

제가 패키지의 위치를 고민할 때 애용하는 규칙이 하나 있어요!
_나의 패키지가 어떤 패키지의 완전한 일부라면 그 패키지의 하위에 둘 것. 아니라면 분리할 것.
완전한 일부의 조건은
다른 것으로 교체될 가능성이 없고
다른 도메인에게도 공유할 가능성이 없는 것_

-

뽀로로를 예로 들어 볼게요!
뽀로로는 손가락을 가지고 있어요. 말랑말랑한 뽀로로 손가락을 나무 손가락이나 강철 손가락으로 대체할 수 있나요? 또는 다른 동물이 뽀로로의 손가락만 뽁 가져가서 필요한 곳에 쓸 수 있나요?
뽀로로손가락은
1. 다른 것으로 변경 가능성이 있거나
2. 다른 도메인에서 가져다 쓸 가능성이 없기 때문에

뽀로로의 완전한 일부이고, 따라서 뽀로로의 하위 도메인이라고 할 수 있습니다.

각 도메인이 패키지라면
뽀로로 패키지의 하위에 손가락 패키지가 위치하는 것이에요.

-

그럼 뽀로로의 안경은 어떨까요?
지금 쓰고있는 멋쟁이 안경은 뿔테 안경이나 별모양 안경으로 바꿔 낄 수 있습니다.
그리고 크롱이 안경을 필요로 할 때 뽀로로의 안경을 뺏어다 쓸 수도 있습니다.
그런 관점에서 뽀로로안경은
1. 다른 것으로 변경될 가능성이 있고
2. 다른 도메인도 필요로 할 가능성이 있기 때문에

뽀로로의 하위 도메인이 아닌, 안경이라는 독립된 도메인이 될 수 있습니다.
뽀로로 패키지와 안경 패키지를 각각 따로 두는 구조가 되겠죠.

-

위의 기준으로 MVC(인증) 미션을 바라보면,
authentication 패키지와 jwt 패키지를 분리하는 것이 더 멋져 보입니다. (고쳐달라는 뜻이 아닙니다!)
'jwt'는 '인증'을 수행하는 다양한 방법 중 하나이고, 그 방법은 다른 것으로 대체될 수 있기 때문인데요,
이 때는 단순히 패키지를 분리하는 것 뿐만 아니라, 인증 방법이 변경되더라도 변경에 유연하도록(OCP) authentication 패키지가 jwt 패키지를 의존하지 않게 인터페이스 등을 잘 활용하는 것도 중요합니다!

---

> Q2. 패키지를 최대한 작게 나누는 게 좋을까요? 패키지 덩어리를 크게 크게 나누는 게 좋을까요?

패키지의 성격에 맞게 적절히 섞어야 한다는 이야기밖에 못 드릴 것 같습니다!
패키지를 독립시킬지, 또는 다른 패키지의 하위에 둘지를 가르는 금서님만의 기준을 세우고 그것을 끝까지 지키는 것이 가장 중요한 것 같아요.

2025-01-08 14:21 UTC, BackFoxx commented on src/main/java/roomescape/authentication/AuthAdminRoleInterceptor.java
> +public class AuthAdminRoleInterceptor implements HandlerInterceptor {
미션 마감까지 시간이 남았으니 멋쟁이 리팩토링 하나만 더 해볼까요? >:D

'인증'의 수단은 jwt 외에 다른 방법으로도 바뀔 수 있기 때문에, 방법이 바뀌어도 변경에 유연하도록 설계하는 것이 중요해요.
그런데 login 패키지, 그리고 authentication 패키지의 직속 클래스들은 jwt 패키지에 강한 결합을 가지고 있는 것 같아요. 이러면 인증 방법이 변경되었을 때 함께 login 패키지와 authentication 패키지도 함께 변경되어야 합니다.

이 강한 결합을 멋지게 떼어내 보아요! :D

2025-01-08 14:25 UTC, BackFoxx commented on src/main/java/roomescape/jwt/JwtProvider.java
> +    }
잘 해주셨어요! 회사에서도 코딩을 사람이 하다 보니 정말 다양한 버그가 일어나는데,
'버그가 일어났다!' 보다도
버그가 일어나서 로그에 남은 메시지가 '서버에 문제가 발생했습니다' 딱 하나일 뿐일 때 정말 괴롭고 눈물이 콸콸 납니다.
예외 처리와 로깅은 꼼꼼하면 꼼꼼할 수록 좋아요! :D

2025-01-08 14:27 UTC, BackFoxx requested changes
피곤하실텐데 새벽에도 리뷰에 코멘트 남겨주시고,,
금서님 정말 짱 멋있어요.
남겨주신 글에 코멘트 남겨드렸어요. 우리 두 개만 더 해봐요! :D

2025-01-09 14:24 UTC, goldm0ng commented on src/main/java/roomescape/jwt/JwtProvider.java
> +    }
네! 예외처리와 로깅을 좀 더 꼼꼼히 할 수 있도록 연습해봐야겠네요!

2025-01-09 14:30 UTC, goldm0ng commented on src/main/java/roomescape/login/LoginRequest.java
> +}
와 예시까지 들어주시며 꼼꼼히 설명해주셔서 감사합니다:)
@Bulider 요녀석 곧 학습해보고 미션이나 프로젝트에 적용해보도록 하겠습니다!!!

2025-01-10 08:02 UTC, goldm0ng commented on src/main/java/roomescape/authentication/AuthAdminRoleInterceptor.java
> +public class AuthAdminRoleInterceptor implements HandlerInterceptor {
기똥찬 예시 덕분에 이해가 쏙쏙 됩니다! 정성스러운 리뷰 감사해요:)

변경에 유연하도록 설계하는 것이 진짜 중요할 것 같아요.. 앞으로 그 점에 유의해야겠네요!
여우님 리뷰하신 거 토대로 인터페이스를 두고 결합을 떼어보았습니다! 이렇게 하는 게 맞는지 모르겠네요. 
리뷰 반영 완료했습니다:)

2025-01-10 08:10 UTC, goldm0ng commented on src/main/java/roomescape/jwt/JwtUtils.java
> +    public static MemberAuthInfo extractMemberAuthInfoFromToken(String token) {
학습 후 질문에 대한 답변을 드리겠습니다!

현재 JwtUtils는 유틸성 클래스라기보다는 Jwt와 관련된 인증 로직을 가진 서비스(?)라고 볼 수 있을 것 같은데요! 이 클래스는 객체 상태인 (secretKey)를 가지고 있고, Spring 빈으로 관리되기도 합니다. 따라서 유틸성 클래스라고 보기는 어려울 것 같아요. 

-> 클래스 이름을 변경하는 방법으로 리팩토링 해보았습니다!

2025-01-10 12:48 UTC, BackFoxx commented on src/main/java/roomescape/authentication/AuthAdminRoleInterceptor.java
> +public class AuthAdminRoleInterceptor implements HandlerInterceptor {
허어어,,, 당신 진짜 최고 천재 천재 짱천재 따봉따봉,, 👍 👍 👍

2025-01-10 13:03 UTC, BackFoxx commented on src/main/java/roomescape/jwt/JwtUtils.java
> +    public static MemberAuthInfo extractMemberAuthInfoFromToken(String token) {
잘 학습해 주셔서 감사해요! 
자바에서는 어떤 클래스나 메서드를 '유틸' 이라고 부르기 위한 기준이 의외로 까다롭다는 걸 알게 되셨을 것 같아요.

유틸성 클래스의 특징인 static 메서드는 객체 간의 의존성을 강하게 결합시키기도 하고,
JwtUtils라는 이름은 말 그대로 Jwt와 관련된 도구이다 보니
jwt와 관련된 수많은 메서드를 구겨넣어서 클래스가 엄청 비대해질 수도 있어요!
그래서 클린 코드를 지향하는 프로젝트에서는 유틸성 클래스를 잘 안 쓰려 해요.

금서님께서 extractor로 리팩토링해주신 것처럼 
이름을 Util보다 더 자세하게 명시하고, 외부에서 주입받아 사용할 수 있게 하면
유지보수하기에도 더 좋은 구조가 되어요 :D

2025-01-10 13:08 UTC, BackFoxx approved these changes
리뷰 잘 반영해주시고, 멋지게 대화 나누어주셔서 고마워요 금서님!
그리디에 합류하고 처음 해보는 리뷰였는데, 금서님 덕분에 정말정말 행복한 코드리뷰 경험이었어요.
다음 미션도 화이팅하세요! :D

2025-01-10 13:08 UTC, merged