[Spring MVC] 김신희 미션 제출합니다.
next-step/spring-basic-roomescape-playground pull request #84
Opened 2024-07-29 06:20 UTC by shinheekim

### 구현 내용
- [ ] 로그인 기능 구현
- [ ] Cookie를 이용해 사용자의 정보를 조회하는 API 구
- [ ] 사용자의 정보를 조회하는 로직 리팩토링
- [ ] 예약 생성 API 및 기능 리팩토링
- [ ] 어드민 페이지 진입은 admin권한이 있는 사람만 할 수 있도록 제한
- [ ] HandlerInterceptor를 활용하여 권한이 없는 경우 401코드 응답

### 어려웠던 내용
강의자료에서 줬던 힌트나 spring-learning-study에서 했던 코드를 참고하며 해봤는데 이전에도 토큰 로그인 방법을 썼지만 Handler를 사용해보니 어려웠습니다. 해당 인증부분에 관해 남은 일주일동안 피드백 받으며 더 공부할 생각입니다. 
또 기존 코드가 주어져있어 이후에 다시 제 스타일대로 리팩토링을 할 예정입니다.

2024-07-29 08:16 UTC, YehyeokBang requested changes
고생하셨습니다!

2024-07-29 08:16 UTC, YehyeokBang commented on src/main/resources/application.properties
> +roomescape.auth.jwt.secret= Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
굳

2024-07-29 08:16 UTC, YehyeokBang commented on src/main/java/roomescape/member/MemberDao.java
> +    }
만약 id가 일치하는 레코드가 없는 경우에는 어떻게 되나요??

2024-07-29 08:16 UTC, YehyeokBang commented on src/main/java/roomescape/member/MemberController.java
> +        String dateHeader = DateTimeFormatter.RFC_1123_DATE_TIME.format(ZonedDateTime.now());
`DateTimeFormatter.RFC_1123_DATE_TIME`가 무엇인지 설명해주실 수 있나요?

2024-07-29 08:16 UTC, YehyeokBang commented on src/main/java/roomescape/member/LoginMemberArgumentResolver.java
> +        }
조건문이 중첩되어 이후 새로운 로직이나 필터링이 필요한 경우 다른 개발자가 이해하기 힘들어질 수도 있을 것 같아요 어떻게 생각하시나요?

2024-07-29 08:16 UTC, YehyeokBang commented on src/main/java/roomescape/interceptor/AdminInterceptor.java
> +    }
`@Component` 어노테이션이 없어도 잘 동작하나요?

2024-08-05 14:57 UTC, shinheekim commented on src/main/java/roomescape/member/MemberController.java
> +        String dateHeader = DateTimeFormatter.RFC_1123_DATE_TIME.format(ZonedDateTime.now());
date, time을 일정 형식에 맞춰주려고 사용을 했고 해당 형식은 아래 사진에 표시한 것과 같습니다!
![image](https://github.com/user-attachments/assets/f03f9f5b-99e5-4395-8215-5698f47235ba)

2024-08-08 17:09 UTC, dd-jiyun reviewed
고생하셨습니다 !

2024-08-08 17:09 UTC, dd-jiyun commented on src/main/java/roomescape/member/MemberController.java
> +    public ResponseEntity<?> createMember(@RequestBody MemberRequest memberRequest) {
해당 메서드에서 제네릭 타입을 쓰신 이유가 있나요?

2024-08-08 17:09 UTC, dd-jiyun commented on src/main/java/roomescape/member/MemberRequest.java
> +public record MemberRequest(
`record`를 사용하신 이유가 있나요??

2024-08-08 17:09 UTC, dd-jiyun commented on src/test/java/roomescape/MissionStepTest.java
> +    void 삼단계() {
테스트 코드 메서드명을 한글로 작성할 경우에 제약이 생길 수 있는 것으로 알고 있어요!
테스트 코드 메서드 명명규칙에 대해서 알아보시면 좋을 것 같습니다 :)

2024-08-08 19:11 UTC, shinheekim commented on src/main/java/roomescape/member/MemberDao.java
> +    }
Dao에서는 단순히 id에 해당하는 member를 찾는 역할을 하고
Service계층에서 해당 member가 null일 경우 예외처리합니다.
```
    public MemberResponse getMemberFromToken(String token) {
        String memberId = Jwts.parserBuilder()
                .setSigningKey(Keys.hmacShaKeyFor(secretKey.getBytes()))
                .build()
                .parseClaimsJws(token)
                .getBody()
                .getSubject();

        Member member = memberDao.findById(Long.parseLong(memberId));
        if (member == null) {
            throw new IllegalArgumentException("찾을 수 없습니다.");
        }
        return new MemberResponse(member.getId(), member.getName(), member.getEmail(), member.getRole());
    }
```

2024-08-08 19:21 UTC, shinheekim commented on src/main/java/roomescape/member/MemberController.java
> +    public ResponseEntity<?> createMember(@RequestBody MemberRequest memberRequest) {
기존에 있던 코드라 따로 건들지 않은 부분입니다! 수정하도록 하겠습니다.

2024-08-08 19:21 UTC, shinheekim commented on src/main/java/roomescape/member/MemberRequest.java
> +public record MemberRequest(
`record`를 사용하면 생성자, getter 등 기본으로 생성해주고 가독성이 좋아 사용하게되었습니다.

2024-08-08 19:30 UTC, shinheekim commented on src/test/java/roomescape/MissionStepTest.java
> +    void 삼단계() {
넵 찾아봤는데 간혹 메서드명이 깨져서 나오는 문제정도로 파악을 했는데 혹시 정확히 어떤 제약이 있는지 공유해주실 수 있나요?

2024-08-08 19:35 UTC, shinheekim commented on src/main/java/roomescape/member/LoginMemberArgumentResolver.java
> +        }
메서드로 따로 분리하는 방법도 있겠지만 변수명, 메서드명이 무엇을하는지 명확하고 depth정도가 2중으로 깊지 않기에 괜찮다고 생각합니다.

2024-08-11 00:05 UTC, YehyeokBang approved these changes
고생하셨습니다!

2024-08-12 16:21 UTC, dd-jiyun approved these changes

2024-08-19 11:26 UTC, merged