[Spring MVC] 최현영 미션 제출합니다.
next-step/spring-basic-roomescape-playground pull request #9
Opened 2024-05-11 09:40 UTC by Martin0o0

ArgumentResolver라는 객체를 처음 접해보며 세션 또는 쿠키의 값을 가공해서 파라미터로 정의된 객체에게 전달하는 것을 알게되었습니다. 
기능을 구현하면서 Jwt와 Cookie를 관리하는 Util 객체를 생성하여 처리하였습니다. 여기서 궁금한 사항은 기존의 자바의 내장 라이브러리들(Long.parseLong()과 같은) 은 Static 키워드를 통해서 객체를 생성하지 않고 전역 메서드을 호출하도록 구현되어 있습니다. Jwt와 Cookie를 가공하고 처리하는 로직이 담긴 유틸리티 클래스를 기존의 자바 라이브러리와 같이 전역으로 메서드를 정의하여 각 레이어에서 활용할 수 있도록 해야할지, 아니면 의존성 주입을 통해 메서드를 호출하는 식으로 진행해야하는지 판단이 되질 않습니다. 따라서 이런 유틸리티 클래스의 메서드는 전역으로 선언하여 호출되도록 하는지, 아니면 Component화 해서 필요한 스프링 빈에서 의존성 주입을 받아 호출되도록 해야는지 궁금합니다.

2024-05-16 12:38 UTC, BGuga requested changes
안녕하세요 현영님 미션 수고하셨습니다 !!
질문 주신 것에 대한 제 생각을 말하기 전에 먼저 [해당 글](https://www.mimul.com/blog/oop-alternative-to-utility-classes/)을 참고 해보셔서 한번 더 고민해보시면 좋을 것 같습니다 ㅎㅎ
반영하시면서 현영님 만의 답을 다시 내려보시고 제 생각도 공유 드리겠습니다!!

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/common/LoginMemberArgumentResolver.java
> +    private MemberService memberService;
사용하지 않으니 삭제해 주세요!!
혹시 MemberService 를 의존했던 이유가 있을까요??

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/common/LoginMemberArgumentResolver.java
> +        return new AuthenticationMember(memberId, name, role);
AuthenticationMember 은 도메인인가요??

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/util/CookieUtil.java
> +    }
CookieUtil 이 로그인 관련 쿠키만 관리하는 것이 좋을 것 같아요!!
그러면 new Cookie("token", ~) 으로 어떤 쿠키 값으로 로그인을 처리하는지 한눈에 볼수 있을 것 같네요!!

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/util/JwtUtil.java
> +                .build()
build 까지의 과정이 중복된 것 같은데 어떻게 제거할 수 있을까요?

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/util/JwtUtil.java
> +
이 값은 공개되면 안될 것 같은데 어떻게 숨길 수 있을까요?

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/reservation/ReservationController.java
> +        ReservationResponse reservation = reservationService.save(authenticationMember, reservationRequest);
제공된 코드지만 @Valid 로 개선해 보는 것이 어떨까요?

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/reservation/ReservationService.java
> +            Reservation reservation = reservationDao.save(reservationRequest);
UI에서 전달된 DTO를 바로 Dao에 전달하셨군요!! 그러면 만약 reservationRequest 에서 theme 를 보내지 않는다면 Default theme 를 적용해야한다는 요구사항이 오면 어떻게 처리할 수 있을까요??

2024-05-16 12:38 UTC, BGuga commented on src/main/java/roomescape/reservation/ReservationRequest.java
> +    }
Dao 가 전달받는 객체를 바꾸신다면 여기 setter도 제거할 수 있을 것 같네요 ㅎㅎ

2024-05-18 05:35 UTC, Martin0o0 commented on src/main/java/roomescape/common/LoginMemberArgumentResolver.java
> +    private MemberService memberService;
처음에 쿠기와 jwt관련된 메서드를 Memberservice에 담아두었는데 Util클래스로 따로 빼는 과정에서 남아있던 것 같습니다. 빠르게 수정하였습니다!

2024-05-18 05:37 UTC, Martin0o0 commented on src/main/java/roomescape/common/LoginMemberArgumentResolver.java
> +        return new AuthenticationMember(memberId, name, role);
엔드포인트 요청 시 쿠키의 토큰 값을 추출해서 사용자의 정보를 반환하여 파마리터로 들어오도록 구현한 Dto 객체입니다.!

2024-05-18 05:39 UTC, Martin0o0 commented on src/main/java/roomescape/util/CookieUtil.java
> +    }
key값은 고정되었다고 생각한다면 보다 직관적일 것 같습니다!

2024-05-18 05:39 UTC, Martin0o0 commented on src/main/java/roomescape/util/CookieUtil.java
> +    }
바로 수정하겠습니다!

2024-05-18 05:57 UTC, Martin0o0 commented on src/main/java/roomescape/util/JwtUtil.java
> +                .build()
JwtUtil 클래스가 스프링 빈으로 등록되어 스프링 컨테이너에서 각각의 객체들이 의존성 주입을 할 수 있는 환경이니, @PostContructor를 사용해서 스프링 빈으로 등록될 시점에 JwtParser를 초기화하는 방식으로 진행하면 될 것 같습니다! 따라서 공통된 JwtParser부분을 init()메서드에 초기화되도록 수정하였습니다!

2024-05-18 06:02 UTC, Martin0o0 commented on src/main/java/roomescape/util/JwtUtil.java
> +
application.properties에 jwt.secret.key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=로 설정하고, 해당 필드에 @Value("${jwt.sercret.key}")로 읽어드려 감출 수 있을 것 같습니다. 허나, application.properties 역시 그대로 노출되어 있기에, jwt.secret.key=${jwt.sercret.key}로 설정 한 뒤, 실행 시 export jwt.sercret.key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=로 환경 변수로 설정하면 될 것 같습니다.

2024-05-18 06:21 UTC, Martin0o0 commented on src/main/java/roomescape/reservation/ReservationService.java
> +            Reservation reservation = reservationDao.save(reservationRequest);
Default Thema의 기본키가 1이라면    private Long theme = 1L;로 설정하면 될 것 같습니다!

2024-05-18 06:21 UTC, Martin0o0 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        ReservationResponse reservation = reservationService.save(authenticationMember, reservationRequest);
수정하였습니다!

2024-05-18 06:29 UTC, Martin0o0 commented
> 안녕하세요 현영님 미션 수고하셨습니다 !! 질문 주신 것에 대한 제 생각을 말하기 전에 먼저 [해당 글](https://www.mimul.com/blog/oop-alternative-to-utility-classes/)을 참고 해보셔서 한번 더 고민해보시면 좋을 것 같습니다 ㅎㅎ 반영하시면서 현영님 만의 답을 다시 내려보시고 제 생각도 공유 드리겠습니다!!
위의 블로그를 참고하고 친구들과 의논하며 제 생각을 정리해볼 시간을 가질 수 있었는데요, 제 생각에는 오직 하나의 행위만 책임(쿠키를 만들거나, 쿠키의 값을 가져오거나 등)지고, 어떤 곳에서 호출을 하던, 특수한 목적만을 하는 메서드는 유틸클래스에서 static으로 만들어서 인스턴스화 없이 단지 클래스의 메서드를 호출하면 된다고 정의를 내렸고, 약간의 비지니스 로직, 혹은 객체마다 다른 결과가 도출되도록 요구되는 클래스가 있다면 컴포넌트화 해서 필요할 때마다 의존성 주입받도록 조치하는 것이 좋지 않을까하는 생각을 하게 되었습니다.

2024-06-10 05:37 UTC, merged